name: EmptyWorld
main: aliuly\emptyworld\Main
version: 1.0.0
api: [1.12.0,2.0.0]
description: An empty world generator
author: aliuly
load: STARTUP
website: https://github.com/alejandroliu/pocketmine-plugins/tree/master/EmptyWorld
